version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.15.0
    steps:
      - checkout
      - run: node --version
      - run: echo "npm installing..."
      - run: npm install
      - run: CI=true npm run build
workflows:
  version: 2.1
  build_test_lint:
    jobs:
      - build
